### ISSUE TITLE
Mouse event handlers broken after ComfyUI frontend 1.24.4 update, will cause the whole node to being dragged.

### ISSUE THREAD

**Issue by o-l-l-i** [o-l-l-i/ComfyUI-Olm-ColorBalance#1]

**Comment by o-l-l-i** [comment]
Should be fixed now, pushed a patch.

**Comment by JohnBaker257** [comment]
Hi, I updated your nodes for the fix and Image adjust now works but Drag crop and Curve editor still have the issue that whole node is dragged instead of doing what is supposed to do, can you please have a look on these nodes as well

**Comment by o-l-l-i** [comment]
@JohnBaker257 Yes, I know this affects all the nodes, I spent quite a few hours fixing these.

I have updated all of the nodes now, these should be good now:

ComfyUI-Olm-ChannelMixer
ComfyUI-Olm-ColorBalance
ComfyUI-Olm-CurveEditor
ComfyUI-Olm-DragCrop
ComfyUI-Olm-Histogram
ComfyUI-Olm-HueCorrect
ComfyUI-Olm-ImageAdjust
ComfyUI-Olm-LGG
ComfyUI-Olm-Sketch

Anyway, thanks for the heads up!

**Comment by JohnBaker257** [comment]
I updated the nodes and both Drag crop and Curve editor now behave correctly, thank you very much
